config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  get "lessons/:id/learn" => "lessons#learn", as: :learn_lesson
  get "lessons/:id/test" => "lessons#test", as: :test_lesson

  resources :lessons do
    member do
      get "vote"
    end
  end

  resources :questions do
    member do
      get "vote"
    end
  end

  resources :answers do
    member do
      get "vote"
    end
  end

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'landings#index'

  devise_scope :user do
    get    "login"   => "devise/sessions#new",         as: :new_user_session
    post   "login"   => "devise/sessions#create",      as: :user_session
    delete "signout" => "devise/sessions#destroy",     as: :destroy_user_session

    get    "signup"  => "devise/registrations#new",    as: :new_user_registration
    post   "signup"  => "devise/registrations#create", as: :user_registration
    put    "signup"  => "devise/registrations#update", as: :update_user_registration
    get    "account" => "devise/registrations#edit",   as: :edit_user_registration
  end

end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  def index
    #Find all the lessons with word 'dog'
    @lessons = Lesson.search params[:search_title], page: params[:page], per_page: 2
    @last_lessons = Lesson.last(5).reverse
  end
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/views/landings/index.html.erb
<%= link_to "Lessons", :lessons %>

<%= form_tag @lesson, :method => 'get' do %>
  <%= label_tag :search_title %>
  <%= text_field_tag :search_title, params[:search_title] %>
  <%= submit_tag :search %>
<% end %>


<% if @lessons.any? %>
  <div class="page-header">
    <h1><%=t '.title', :default => "Finded lessons" %></h1>
  </div>
  <div class="col-md-12">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>ID</th>
          <th>Lesson title</th>
          <th>Created at</th>
          <th><%=t '.actions', :default => t("helpers.actions") %></th>
        </tr>
      </thead>
      <tbody>
        <% @lessons.each do |lesson| %>
          <tr>
            <td><%= lesson.id %></td>
            <td><%= lesson.lesson_title %></td>
            <td><%=l lesson.created_at, format: :long %></td>
            <td>
              <%= link_to lesson_path(lesson), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
                <%= glyph 'info-sign' %>
                <%= glyph 'pencil' %>
              <%- end -%>
              <%= link_to lesson_path(lesson), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
                <%= glyph 'remove' %>
              <%- end -%>
              <%= link_to learn_lesson_path(lesson), :method => "GET", :class => 'btn btn-xs', :title => "#{ t('.learn', :default => t('helpers.links.learn')) }" do %>
                <%= glyph 'pencil' %>
              <%- end -%>
              <%= link_to test_lesson_path(lesson), :method => "GET", :class => 'btn btn-xs', :title => "#{ t('.test', :default => t('helpers.links.test')) }" do %>
                <%= glyph 'info-sign' %>
              <%- end -%>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @lessons %>
  </div>
<% end %>

<div class="col-md-6">
  <h3>Last added</h3>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>ID</th>
        <th>Lesson title</th>
        <th>Created at</th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% @last_lessons.each do |lesson| %>
        <tr>
          <td><%= lesson.id %></td>
          <td><%= lesson.lesson_title %></td>
          <td><%=l lesson.created_at, format: :long %></td>
          <td>
            <%= link_to lesson_path(lesson), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
              <%= glyph 'info-sign' %>
            <%- end -%>
            <%= link_to lesson_path(lesson), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
              <%= glyph 'remove' %>
            <%- end -%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="col-md-6">
  <h3>Last added</h3>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>ID</th>
        <th>Lesson title</th>
        <th>Created at</th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% @last_lessons.each do |lesson| %>
        <tr>
          <td><%= lesson.id %></td>
          <td><%= lesson.lesson_title %></td>
          <td><%=l lesson.created_at, format: :long %></td>
          <td>
            <%= link_to lesson_path(lesson), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
              <%= glyph 'info-sign' %>
            <%- end -%>
            <%= link_to lesson_path(lesson), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
              <%= glyph 'remove' %>
            <%- end -%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>